version: '2'

services:
  mongo:  
    network_mode: "host"
    restart: always
    image: mvertes/alpine-mongo:3.2.3
    volumes:
      - ./db/:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles

